---
title: "Single cell perspective into Extracellular Vesicules projected onto Spatial Transcriptomics"
format:
  html:
    code-fold: true
    code-tools: true
    embed-resources: true
    self-contained-math: true
jupyter: python3
---

# Load in data

Set up the environment and load the deps:

```{python}
#| output: false

import re
import pandas as pd
pd.set_option('display.max_columns', 100)
import scanpy as sc
import omicverse as ov
import anndata as an
import numpy as np
import seaborn as sns
import plotly.express as px
import dash_bio
import seaborn.objects as so
import matplotlib.pyplot as plt
from pathlib import Path
from os import getenv
from dotenv import load_dotenv
from scipy.sparse import csr_matrix
from scipy.stats import ttest_ind
from scipy.stats import spearmanr
from scipy.stats import f_oneway
from scipy.stats import tukey_hsd
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from sklearn.decomposition import PCA
from scipy.cluster.hierarchy import linkage, dendrogram, fcluster
from matplotlib.gridspec import GridSpec
from matplotlib.patches import Patch

## Do you want to rerun all the models?
rerun_all = True

## load the environment variables from the .env file
load_dotenv()

anndata_folder = getenv("ANNDATA_FOLDER")
atlas_folder = getenv("ATLAS_FOLDER")
data_folder = getenv("DATA_FOLDER")
st_folder = getenv("ST_FOLDER")
model_folder = Path(data_folder).expanduser() / "saved_models"
raw_data_folder = getenv("RAW_DATA_FOLDER")



# some prelims for data standardisation
replace_dict = {
  "Proliferative Early": "EP",
  "Proliferative Late": "LP",
  "Secretory Early": "ES",
  "Secretory Mid": "MS",
  "Secretory Late": "LS",
  "Secretory Early-Mid": "MS",
  # "Secretory": "Secretory Mid",
  "Mid-Secretory": "MS",
  "Proliferative Disordered": "EP"
}

## the order that the variable shoudl be in 
gen_celltype_order = [
  "Ciliated Epithelium",
  "Epithelium",
  "Stromal",
  "Mesenchymal",
  "Vascular",
  "Immune",
  "Other",
  "Unknown"
]

## the celltype generalisation
gen_celltype_dict = {
  "Ciliated": gen_celltype_order[0],
  "preCiliated": gen_celltype_order[0],
  "SOX9_basalis": gen_celltype_order[1],
  "SOX9_functionalis_I": gen_celltype_order[1],
  "SOX9_functionalis_II": gen_celltype_order[1],
  "SOX9_luminal": gen_celltype_order[1],
  "Cycling": gen_celltype_order[1],
  "preGlandular": gen_celltype_order[1],
  "Glandular": gen_celltype_order[1],
  "Glandular_secretory": gen_celltype_order[1],
  "Glandular_secretory_FGF7": gen_celltype_order[1],
  "Luminal": gen_celltype_order[1],
  "preLuminal": gen_celltype_order[1],
  "MUC5B": gen_celltype_order[1],
  "KRT5": gen_celltype_order[1],
  "eStromal": gen_celltype_order[2],
  "eStromal_early": gen_celltype_order[2],
  "eStromal_mid": gen_celltype_order[2],
  "eStromal_late": gen_celltype_order[2],
  "dStromal_early": gen_celltype_order[2],
  "dStromal_mid": gen_celltype_order[2],
  "dStromal_late": gen_celltype_order[2],
  "dStromal": gen_celltype_order[2],
  "eStromal_MMPs": gen_celltype_order[2],
  "eStromal_cycling": gen_celltype_order[2],
  "uSMCs": gen_celltype_order[3],
  "mPV": gen_celltype_order[3],
  "ePV_1a": gen_celltype_order[3],
  "ePV_1b": gen_celltype_order[3],
  "ePV_2": gen_celltype_order[3],
  "Fibroblast_basalis": gen_celltype_order[3],
  "HOXA13": gen_celltype_order[3],
  "Arterial": gen_celltype_order[4],
  "Venous": gen_celltype_order[4],
  "Lymphatic": gen_celltype_order[4],
  # "eHormones": gen_celltype_order[6],
  # "sHormones": gen_celltype_order[6],
  # "dHormones": gen_celltype_order[6],
  "Immune_Lymphoid": gen_celltype_order[5],
  "Immune_Myeloid": gen_celltype_order[5]
}

```

Load in the data, filter out "Hormones" celltypes and non-endometriotic samples and finally do some preprocessing:

```{python}
#| output: false

## Load the main HECA dataset
sc_dat = sc.read_h5ad(
  Path(raw_data_folder).expanduser() / "endometriumAtlasV2_cells_with_counts.h5ad",
  backed = "r"
)

sc_dat_immu = sc.read_h5ad(
  Path(raw_data_folder).expanduser() / "endometriumAtlasV2_cells_immune.h5ad",
  backed = "r"
)

sc_dat.obs = (
  sc_dat.obs
  .assign(
    cyclephase=lambda x: x.Stage.replace(replace_dict).astype("category"),
    celltype_general=lambda x: x.celltype.cat.remove_unused_categories(),
    celltype=lambda x: 
      x.celltype
      .astype("object")
      .mask(
        x.index.isin(sc_dat_immu.obs.celltype.index), 
        sc_dat_immu.obs.celltype.astype("object")
      )
      .astype("category")
  )
  .replace({ "celltype_general": gen_celltype_dict })
  .assign(celltype_general=lambda x: 
    pd.Categorical(x.celltype_general, categories = gen_celltype_order, ordered=True))
  .rename(columns={"sample": "samplename"})
)

## exclude some celltypes, such as she hormones cell types
## also exclude the endometriosis samples
the_condition = "celltype not in ['eHormones', 'sHormones', 'dHormones'] & Endometrial_pathology == 'C'"
sc_dat = sc_dat[sc_dat.obs.query(the_condition).index, :]

sc_dat = ov.pp.preprocess(sc_dat.to_memory(), mode="shiftlog|pearson", n_HVGs=3000, target_sum=1e4)
# sc_dat = sc_dat[:, sc_dat.var.highly_variable_features]
# check the minimum size of celltype matrix after filtering
# np.min([sc_dat.obs.groupby(["Stage", "celltype"]).apply(lambda x: sc_dat[x.index, :].X.size)])

## load in the EV CCHT only data
ccht_uf_raw = pd.read_feather(Path(data_folder).expanduser() / "filtered" / "annot_raw.feather").set_index("gene_id")
ccht_uf_pheno = pd.read_table(Path(data_folder).expanduser() / "filtered" / "phenotype.tsv").set_index("samplename")

```

Load in the spatial slides experiments

```{python}
#| output: false

slides_path = Path(st_folder).expanduser()
vis_dats = {}
for vis_fold in slides_path.glob("*/"):
  slide_id = vis_fold.stem
  print("Working on slide " + str(slide_id))
  vis_dat = sc.read_visium(path=vis_fold / "outs")
  vis_dat.var_names_make_unique()
  vis_dat.var["mt"] = vis_dat.var_names.str.startswith("MT-")
  sc.pp.calculate_qc_metrics(vis_dat, qc_vars=["mt"], inplace=True)

  vis_dat = vis_dat[:, vis_dat.var['total_counts'] > 100]
  vis_dat = ov.pp.preprocess(vis_dat, mode='shiftlog|pearson', n_HVGs=3000, target_sum=1e4)
  ## new recommended preproc - does not work
  # vis_dat = ov.space.svg(vis_dat, mode="prost", n_svgs=3000, target_sum=1e4, platform="visium")
  vis_dat.raw = vis_dat
  vis_dat = vis_dat[:, vis_dat.var.highly_variable_features]
  vis_dats[slide_id] = vis_dat
  # adata_sp

vis_keys = list(vis_dats.keys())

```

# Bulk deconvolution and projection onto single cells

We'd be interested in using scRNA-seq atlas to deconvolve the EV data. This helps us understand where are those EV produced and which tissue signal they are capturing. To run single cell and projection, we are gonna use [TAPE](https://www.nature.com/articles/s41467-022-34550-9) algorithm. This algorithm also enables us to use the trained VAE model to estimate the number and the distribution of original cell populations.

First we'll need to reformat the raw bulk RNA samples from EV to matrix form and prepare some plotting functions.

```{python}
#| output: false

## switch the expression matrix to raw counts if the matrix is preprocessed
sc_dat.layers["scaled"] = sc_dat.X
sc_dat.X = sc_dat.layers["counts"]
del sc_dat.layers["counts"]

model_params = {
  "celltype_key": "celltype",
  "top_marker_num": 500,
  "max_single_cells": 5000,
  "ratio_num": 1,
  "gpu": 0
}

frac_params = {
  "batch_size": 512,
  "epochs": 5, # looking at loss plot then 500 seems to be already enough, and we don't need the fractions really
  "scaler": "ss", # seems to harmonise distributions better
  "method": "tape",
  "mode": "high-resolution"
}

vae_params = {
  "batch_size": 512,
  "hidden_size": 256,
  "epoch_num": 10 # looking at loss plot then 500 seems to be already enough
}

```

Train the model on the single cell reference data and generate the pseudo-single-cell data from the bulk samples. Here we divide the original dataset into "biopsy" and "EV" groups, which then summarises all of the corresponding sampling method samples into one representative group. This would also increase the confidence of cell profiles while normalising individual variance.

::: {.panel-tabset}

## EV group

```{python}

gen_sc_file = Path(anndata_folder).expanduser() / "gen_sc_ev.h5ad"
if gen_sc_file.exists() and not rerun_all:
  gen_ccht_ev = sc.read_h5ad(gen_sc_file, backed="r").to_memory()
else:
  model_obj = ov.bulk2single.Bulk2Single(
    bulk_data=ccht_uf_raw[ccht_uf_pheno.query("group=='UF'").index],
    single_data=sc_dat.to_memory(),
    **model_params
  )
  # you have to run this to set the model_obj.cell_target_sum  
  # and not run the single_preprocess_lazy() as it seems to override cell_num attribute and does needless normalisation
  _ = model_obj.predicted_fraction(**frac_params)
  model_obj.bulk_preprocess_lazy()
  model_obj.train(
    vae_save_dir=Path(model_folder).expanduser() / "pseudosc_model",
    vae_save_name="pseudosc_ev",
    generate_save_dir=Path(model_folder).expanduser() / "pseudosc_gen",
    generate_save_name="pseudosc_ev_gen",
    **vae_params
    )
  gen_ccht_ev = model_obj.generate()
  gen_ccht_ev.obs = gen_ccht_ev.obs.join(
    sc_dat.obs[["celltype", "celltype_general"]].drop_duplicates().set_index("celltype"), 
    on="celltype"
    )
  gen_ccht_ev.write(gen_sc_file)
  del model_obj

```

The generated dataset is then preprocessed, scaled, embedded into lower dimensions and clustered via Leiden.

```{python}

gen_ccht_ev = ov.pp.preprocess(gen_ccht_ev, mode="shiftlog|pearson", n_HVGs=2000)
ov.pp.scale(gen_ccht_ev)
ov.pp.pca(gen_ccht_ev, layer='scaled', n_pcs=50)

gen_ccht_ev.obsm['X_pca']=gen_ccht_ev.obsm['scaled|original|X_pca']
ov.pl.embedding(
  gen_ccht_ev,
  basis='X_pca',
  color='celltype',
  frameon='small'
  )

ov.pp.neighbors(
  gen_ccht_ev, 
  n_neighbors=15, 
  n_pcs=50,
  use_rep='scaled|original|X_pca'
  )

ov.pp.umap(gen_ccht_ev)

ov.pl.embedding(
  gen_ccht_ev,
  basis='X_umap',
  color='celltype',
  frameon='small'
  )

```

## Biopsy group

```{python}

gen_sc_file = Path(anndata_folder).expanduser() / "gen_sc_biopsy.h5ad"
if gen_sc_file.exists() and not rerun_all:
  gen_ccht_bio = sc.read_h5ad(gen_sc_file, backed="r").to_memory()
else:
  model_obj = ov.bulk2single.Bulk2Single(
    bulk_data=ccht_uf_raw[ccht_uf_pheno.query("group=='biopsy'").index],
    single_data=sc_dat.to_memory(),
    **model_params
  )
  _ = model_obj.predicted_fraction(**frac_params) # you have to run this to set the model_obj.cell_target_sum
  model_obj.bulk_preprocess_lazy()
  model_obj.train(
    vae_save_dir=Path(model_folder).expanduser() / "pseudosc_model",
    vae_save_name="pseudosc_bio",
    generate_save_dir=Path(model_folder).expanduser() / "pseudosc_gen",
    generate_save_name="pseudosc_bio_gen",
    **vae_params
    )
  gen_ccht_bio = model_obj.generate()
  gen_ccht_bio.obs = gen_ccht_bio.obs.join(
    sc_dat.obs[["celltype", "celltype_general"]].drop_duplicates().set_index("celltype"), 
    on="celltype"
    )
  gen_ccht_bio.write(gen_sc_file)
  del model_obj

```

The generated dataset is then preprocessed, scaled, embedded into lower dimensions and clustered via Leiden.

```{python}

gen_ccht_bio = ov.pp.preprocess(gen_ccht_bio, mode="shiftlog|pearson", n_HVGs=2000)
ov.pp.scale(gen_ccht_bio)
ov.pp.pca(gen_ccht_bio, layer='scaled', n_pcs=50)

gen_ccht_bio.obsm['X_pca']=gen_ccht_bio.obsm['scaled|original|X_pca']
ov.pl.embedding(
  gen_ccht_bio,
  basis='X_pca',
  color='celltype',
  frameon='small'
  )

ov.pp.neighbors(
  gen_ccht_bio, 
  n_neighbors=15, 
  n_pcs=50,
  use_rep='scaled|original|X_pca'
  )

ov.pp.umap(gen_ccht_bio)

ov.pl.embedding(
  gen_ccht_bio,
  basis='X_umap',
  color='celltype',
  frameon='small'
  )

```

:::


# Projection of generated counts to Spatial Transcriptomic slides

And now use the generated pseudo-single-cell dataset and project it to the spatial transcriptomic slide.

## Single2Spatial

First, we are trying out the Single2Spatial VAE based spatial deconvolution method. This has the benefit of being able to generalise the profiles better, but at the price of using more GPU compute resource. This means that we will have to scale down the number of cells included in the projection, and therefore would significantly affect the accuracy of the deconvolution.

```{python}
#| output: false

model_params = {
  "celltype_key": "celltype",
  "top_marker_num": 500,
  "gpu": -1 # the default parameter is too large for the GPU
}

vae_params = {
  "batch_size": 512,
  "hidden_size": 256,
  "spot_num": 500,
  "cell_num": 100,
  "num_epochs":1000,
  "k": 10
}

```


::: {.panel-tabset}

### EV group

```{python}

gen_st_file = Path(anndata_folder).expanduser() / "gen_st_ev.h5ad"
if gen_st_file.exists() and not rerun_all:
  vis_dat_proj = sc.read_h5ad(gen_st_file, backed="r").to_memory()
else:
  # clean up on the model object and train the single2spatial model
  model_obj = ov.bulk2single.Single2Spatial(
    single_data=gen_ccht_ev.to_memory(),
    spatial_data=vis_dats["E184-1_bottom"].to_memory(),
    **model_params
  )
  model_obj.train(
    df_save_dir=Path(model_folder).expanduser() / "pseudosc_st_model",
    df_save_name="pseudosc_st_ev",
    **vae_params
  )
  vis_dat_proj = model_obj.spot_assess()
  vis_dat_proj.write(gen_st_file)
  del model_obj

# reformat the obs layer to have intensities per maximum cell type predicted
vis_dat_proj.obs = (
  vis_dat_proj.obs
  .assign(
    cell_type_max = lambda x:
      x.filter(items=gen_ccht_ev.obs.celltype.unique()).max().idxmax()
  )
)

```

The dataset visualised

```{python}

# TODO multiclass colors for each major cell type group
ct_group = gen_ccht_ev.obs.celltype_general.unique()
for ct_g in ct_group:
  cts = gen_ccht_ev.obs.query("celltype_general==@ct_g").celltype.unique()
  sc.pl.spatial(
    vis_dat_proj,
    title=ct_g,
    cmap='magma',
    color=cts,
    ncols=3, size=1.3,
    img_key='hires',
    # limit color scale at 99% quantile of cell abundance
    vmin=0, vmax='p95'
  )

```

### Biopsy group

```{python}

gen_st_file = Path(anndata_folder).expanduser() / "gen_st_bio.h5ad"
if gen_st_file.exists() and not rerun_all:
  vis_dat_proj = sc.read_h5ad(gen_st_file, backed="r").to_memory()
else:
  # clean up on the model object and train the single2spatial model
  model_obj = ov.bulk2single.Single2Spatial(
    single_data=gen_ccht_bio.to_memory(),
    spatial_data=vis_dats["E184-1_bottom"].to_memory(),
    **model_params
  )
  model_obj.train(
    df_save_dir=Path(model_folder).expanduser() / "pseudosc_st_model",
    df_save_name="pseudosc_st_bio",
    **vae_params
  )
  vis_dat_proj = model_obj.spot_assess()
  vis_dat_proj.write(gen_st_file)
  del model_obj

# reformat the obs layer to have intensities per maximum cell type predicted
vis_dat_proj.obs = (
  vis_dat_proj.obs
  .assign(
    cell_type_max = lambda x:
      x.filter(items=gen_ccht_bio.obs.celltype.unique()).max().idxmax()
  )
)

```

The dataset visualised

```{python}

# TODO multiclass colors for each major cell type group
ct_group = "Stromal"
cts = gen_ccht_bio.obs.query("celltype_general==@ct_group").celltype.unique()
sc.pl.spatial(
  vis_dat_proj,
  cmap='magma',
  color=cts,
  ncols=3, size=1.3,
  img_key='hires',
  # limit color scale at 99% quantile of cell abundance
  vmin=0, vmax='p95',
  spot_size=1
)

```

::: 

## Tangram + cell2location

Next, we try out the classical spatial deconvolution method `Tangram` to integrate the Visium slide and the generated scRNA-seq dataset. Then, we apply `cell2location` to perform spatial deconvoluion. The benefit of this approach is that it is less computationally heavy and we are not anymore limited by GPU VRAM, while being still performing on par with previous methods.

::: {.panel-tabset}

## EV group

```{python}

gen_st_file = Path(anndata_folder).expanduser() / "c2l_st_ev.h5ad"
if gen_st_file.exists() and not rerun_all:
  vis_dat_proj = sc.read_h5ad(gen_st_file, backed="r").to_memory()
else:
  model_obj = ov.space.Tangram(
    gen_ccht_ev.to_memory(),
    vis_dats["E184-1_bottom"].to_memory(),
    clusters="celltype"
  )
  model_obj.train(mode="cells", num_epochs=500, device="cuda:0")
  vis_dat_proj = model_obj.cell2location()
  vis_dat_proj.write(gen_st_file)
  del model_obj

```

Visualise the results

```{python}

# TODO multiclass colors for each major cell type group
ct_group = "Stromal"
cts = gen_ccht_ev.obs.query("celltype_general==@ct_group").celltype.unique()
sc.pl.spatial(
  vis_dat_proj,
  cmap='magma',
  color=cts,
  ncols=3, size=1.3,
  img_key='hires',
  # limit color scale at 99% quantile of cell abundance
  vmin=0, vmax='p95'
)

```

## Biopsy group

```{python}

gen_st_file = Path(anndata_folder).expanduser() / "c2l_st_bio.h5ad"
if gen_st_file.exists() and not rerun_all:
  vis_dat_proj = sc.read_h5ad(gen_st_file, backed="r").to_memory()
else:
  model_obj = ov.space.Tangram(
    gen_ccht_bio.to_memory(),
    vis_dats["E184-1_bottom"].to_memory(),
    clusters="celltype"
  )
  model_obj.train(mode="cells", num_epochs=500, device="cuda:0")
  vis_dat_proj = model_obj.cell2location()
  vis_dat_proj.write(gen_st_file)
  del model_obj

```

Visualise the results

```{python}

# TODO multiclass colors for each major cell type group
ct_group = "Stromal"
ct_group = gen_ccht_bio.obs.celltype_general.unique()[1]
cts = gen_ccht_bio.obs.query("celltype_general==@ct_group").celltype.unique()
sc.pl.spatial(
  vis_dat_proj,
  cmap='magma',
  color=cts,
  ncols=3, size=1.3,
  img_key='hires',
  # limit color scale at 99% quantile of cell abundance
  vmin=0, vmax='p95'
)

```

:::
